# Generated by Django 5.2.5 on 2025-08-09 06:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(verbose_name='النص الأصلي')),
                ('reversed_text', models.TextField(verbose_name='النص المعكوس')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'إدخال نص',
                'verbose_name_plural': 'إدخالات النصوص',
                'ordering': ['-created_at'],
            },
        ),
    ]
