# Generated by Django 5.2.5 on 2025-08-23 06:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القسم')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='رمز القسم')),
                ('description', models.TextField(blank=True, verbose_name='وصف القسم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='الرقم الوظيفي')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='رقم الهاتف')),
                ('office_number', models.CharField(blank=True, max_length=20, verbose_name='رقم المكتب')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher_photos/', verbose_name='الصورة')),
                ('rank', models.CharField(choices=[('lecturer', 'محاضر'), ('assistant_professor', 'أستاذ مساعد'), ('associate_professor', 'أستاذ مشارك'), ('professor', 'أستاذ')], max_length=20, verbose_name='الدرجة العلمية')),
                ('employment_type', models.CharField(choices=[('full_time', 'دوام كامل'), ('part_time', 'دوام جزئي'), ('contract', 'متعاقد'), ('visiting', 'زائر')], max_length=15, verbose_name='نوع التوظيف')),
                ('specialization', models.CharField(max_length=100, verbose_name='التخصص')),
                ('hire_date', models.DateField(verbose_name='تاريخ التوظيف')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الراتب')),
                ('years_of_experience', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='سنوات الخبرة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.department', verbose_name='القسم')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'معلم',
                'verbose_name_plural': 'المعلمون',
                'ordering': ['user__first_name', 'user__last_name'],
                'permissions': [('can_view_all_students', 'يمكن عرض جميع الطلاب'), ('can_edit_student_grades', 'يمكن تعديل درجات الطلاب'), ('can_generate_reports', 'يمكن إنشاء التقارير'), ('can_manage_department', 'يمكن إدارة القسم'), ('can_view_teacher_salaries', 'يمكن عرض رواتب المعلمين')],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to='teachers.teacher', verbose_name='رئيس القسم'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='رمز المقرر')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المقرر')),
                ('description', models.TextField(blank=True, verbose_name='وصف المقرر')),
                ('credit_hours', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='الساعات المعتمدة')),
                ('semester', models.CharField(max_length=20, verbose_name='الفصل الدراسي')),
                ('year', models.IntegerField(verbose_name='السنة الدراسية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.department', verbose_name='القسم')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='المدرس')),
            ],
            options={
                'verbose_name': 'مقرر',
                'verbose_name_plural': 'المقررات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TeacherPermissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='الإجراء')),
                ('permission', models.CharField(max_length=100, verbose_name='الصلاحية')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'سجل صلاحية',
                'verbose_name_plural': 'سجلات الصلاحيات',
                'ordering': ['-timestamp'],
            },
        ),
    ]
