# Generated by Django 5.2.5 on 2025-08-23 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone Number')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(100)], verbose_name='Age')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='Student ID')),
                ('year', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], max_length=1, verbose_name='Academic Year')),
                ('gpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='GPA')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/', verbose_name='Photo')),
                ('date_enrolled', models.DateField(auto_now_add=True, verbose_name='Date Enrolled')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
