# Generated by Django 5.2.5 on 2025-08-23 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_options_alter_student_address_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='الدرجة')),
                ('date_recorded', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.course', verbose_name='المقرر')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'درجة',
                'verbose_name_plural': 'الدرجات',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
